---
- name: HashiCorp GPGキーの取得と登録
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

- name: Vaultリポジトリの追加
  shell: |
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" > /etc/apt/sources.list.d/hashicorp.list

- name: Vaultをインストール
  apt:
    name: vault
    state: present
    update_cache: true

- name: Vault devモードでバックグラウンド起動
  shell: |
    nohup vault server -dev -dev-root-token-id="root" > /tmp/vault.log 2>&1 &
    sleep 3

- name: Vault環境変数の設定
  lineinfile:
    path: ~/.bashrc
    line: 'export VAULT_ADDR="http://127.0.0.1:8200"'
    create: yes
