---
- name: VaultのDatabaseエンジンを有効化
  shell: vault secrets enable database || true

- name: VaultにPostgreSQL接続設定を登録
  command: >
    vault write database/config/postgres
    plugin_name=postgresql-database-plugin
    allowed_roles=myapp
    connection_url="postgresql://postgres:{{postgres_password}}@127.0.0.1:5432/postgres?sslmode=disable"
  environment:
    VAULT_ADDR: "http://127.0.0.1:8200"

- name: VaultにRoleを作成
  shell: >
    VAULT_ADDR=http://127.0.0.1:8200 vault write database/roles/{{ name }}
    db_name=postgres
    creation_statements="CREATE ROLE \"{{ name }}\" WITH LOGIN PASSWORD '{{ postgres_password }}' VALID UNTIL '1h';"
    default_ttl="60s"
    max_ttl="5m"
